version: '3.8'
services:
  odoo:
    image: registry.3roots.live/odoo:15-ee
    container_name: odoo
    ports:
      - 8069:8069
    networks:
      - odoo_network
    depends_on:
      - db
    volumes:
      - odoo-data:/var/lib/odoo
      - .:/mnt/extra-addons
    environment: 
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres
    container_name: db
    networks:
      - odoo_network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  odoo-data:
  db-data:
networks:
  odoo_network:
